// <auto-generated />
using ContactsContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ContactsContext.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    [Migration("20180202211320_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactsContext.DbModels.CategoryPerson", b =>
                {
                    b.Property<int>("CategoryPersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryPersonName");

                    b.HasKey("CategoryPersonId");

                    b.ToTable("CategoryPersons");
                });

            modelBuilder.Entity("ContactsContext.DbModels.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryPersonId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("PersonId");

                    b.HasIndex("CategoryPersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ContactsContext.DbModels.Person", b =>
                {
                    b.HasOne("ContactsContext.DbModels.CategoryPerson", "CategoryPerson")
                        .WithMany("Persons")
                        .HasForeignKey("CategoryPersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
